#!/usr/bin/env bash

#
# This script is run on a created instance to initialize it as a masterless
# git-based salt node. It's job is to: 
# 
#   * install salt, and 
#   * set up this instance as a self-managed salt minion. 
#

LOGFILE=/root/bootstrap.log
DATE_FMT="+%Y-%m-%d %H:%M:%S%z"
HERE=$(dirname $0)
SALT_CONFIG=$HERE/minion

function log() {
    NOW=$(date "${DATE_FMT}")
    echo "${NOW}: $*" | tee -a ${LOGFILE}
}

log "begin bootstrap."

log "adding salt ppa."
add-apt-repository ppa:saltstack/salt -y

log "updating package information..."
apt-get --assume-yes update | tee -a ${LOGFILE}

log "installing salt..."
apt-get --assume-yes install salt-minion | tee -a ${LOGFILE}

log "configuring salt..."

# We'll use this configuration now to bootstrap this instance.
echo "master: localhost" > $SALT_CONFIG
echo "file_client: local" >> $SALT_CONFIG
echo "file_roots: {base: [${HERE}/salt]}" >> $SALT_CONFIG

# This configuration will be used from the first update onwards.
mv ${HERE}/minion-config /etc/salt/minion | tee -a ${LOGFILE}

log "bootstrapping salt masterless configuration..."
salt-call -c $HERE state.highstate | tee -a ${LOGFILE}

log "done."
sudo -u lantern touch /home/lantern/.bootstrap-done
