#!/usr/bin/env bash

SALT_DIR=/srv/salt
DIRTY_FILE=${SALT_DIR}/.dirty

function die() {
    logger $*
    exit 1
}

umask 027

#
# Overwrite the system salt folder with the contents of the puppet folder in
# this repository
#
logger "gitsalt repo updated, replacing ${SALT_DIR}."
/usr/bin/git archive --format=tar HEAD salt/modules | (cd ${SALT_DIR} && rm -rf * && /bin/tar xf - --strip-components 1) || die "Failed to replace config"
# signal need to update config due to push
touch ${DIRTY_FILE}
logger "finished replacing salt configuration."
